# Generated by Django 3.0.7 on 2020-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=100)),
                ('level', models.CharField(default='Sailors', max_length=20)),
            ],
        ),
    ]
