# Generated by Django 3.0.7 on 2020-08-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_auto_20200811_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirimpesan',
            name='penerima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spenerima', to='sekolah.Student'),
        ),
        migrations.AlterField(
            model_name='kirimpesan',
            name='pengirim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pengirim', to='sekolah.Student'),
        ),
    ]
