# Generated by Django 3.0.7 on 2020-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_angkatan_angkatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='xpminggu',
            field=models.IntegerField(default=0),
        ),
    ]
