# Generated by Django 3.0.7 on 2020-07-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_student_xpminggu'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hp_pot',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(default='', max_length=40)),
                ('week', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.Student')),
            ],
        ),
    ]
