# Generated by Django 3.0.7 on 2020-08-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0010_auto_20200812_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirimpesan',
            name='penerima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penerima', to='sekolah.Student'),
        ),
    ]
