# Generated by Django 3.0.7 on 2020-08-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0012_auto_20200813_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirimpesan',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kirimpesan',
            name='pesan',
            field=models.CharField(default='Tidak ada pesan', max_length=40),
        ),
    ]
