# Generated by Django 3.0.8 on 2020-07-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiMinggu1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_int', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Rapot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keaktifan_text', models.CharField(default='', max_length=2)),
                ('pemahamanMateri_text', models.CharField(default='', max_length=2)),
                ('kedisiplinan_text', models.CharField(default='', max_length=2)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentScores',
        ),
    ]
