# Generated by Django 3.0.8 on 2020-07-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
