# Generated by Django 3.0.8 on 2020-07-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200704_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilaiminggu1',
            old_name='nilai_int',
            new_name='nilai',
        ),
        migrations.RenameField(
            model_name='rapot',
            old_name='keaktifan_text',
            new_name='keaktifan',
        ),
        migrations.RenameField(
            model_name='rapot',
            old_name='kedisiplinan_text',
            new_name='kedisiplinan',
        ),
        migrations.RenameField(
            model_name='rapot',
            old_name='pemahamanMateri_text',
            new_name='pemahamanMateri',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rank_int',
            new_name='rank',
        ),
    ]
