# Generated by Django 3.0.8 on 2020-07-05 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200704_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilaiminggu1',
            old_name='nilai',
            new_name='nilai1',
        ),
        migrations.CreateModel(
            name='NilaiMinggu3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai3', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiMinggu2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai2', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
    ]
