# Generated by Django 3.0.8 on 2020-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200710_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nomor',
            field=models.IntegerField(default=0),
        ),
    ]
