# Generated by Django 3.0.8 on 2020-07-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200705_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaiminggu1',
            name='nilai1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
