# Generated by Django 3.0.8 on 2020-07-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_student_nomor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nomor',
        ),
    ]
