# Generated by Django 3.0.8 on 2020-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_student_nomor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nomor',
            field=models.IntegerField(default=0),
        ),
    ]
