# Generated by Django 3.0.8 on 2020-07-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200705_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nilai1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nilai2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nilai3',
        ),
        migrations.CreateModel(
            name='Rapot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keaktifan', models.CharField(default='', max_length=2)),
                ('pemahamanMateri', models.CharField(default='', max_length=2)),
                ('kedisiplinan', models.CharField(default='', max_length=2)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiMinggu3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai3', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiMinggu2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai2', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
        migrations.CreateModel(
            name='NilaiMinggu1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai1', models.IntegerField(default=0, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Student')),
            ],
        ),
    ]
