# Generated by Django 3.0.8 on 2020-07-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_student_nomor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nomor',
        ),
    ]
