# Generated by Django 3.0.8 on 2020-07-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200705_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaiminggu2',
            name='student',
        ),
        migrations.RemoveField(
            model_name='nilaiminggu3',
            name='student',
        ),
        migrations.RemoveField(
            model_name='rapot',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='nilai1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='nilai2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='nilai3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.DeleteModel(
            name='NilaiMinggu1',
        ),
        migrations.DeleteModel(
            name='NilaiMinggu2',
        ),
        migrations.DeleteModel(
            name='NilaiMinggu3',
        ),
        migrations.DeleteModel(
            name='Rapot',
        ),
    ]
